### ISSUE TITLE
Fix the linting problem

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty-puppet-lark#4]
```shell
$ git pull

$ npm install

$ npm test

> wechaty-pguppet-lark@0.3.1 test
> npm run lint && npm run test:unit


> wechaty-pguppet-lark@0.3.1 lint
> npm run lint:es && npm run lint:ts && npm run lint:md


> wechaty-pguppet-lark@0.3.1 lint:es
> eslint --ignore-pattern fixtures/ 'src/**/*.ts' 'tests/**/*.ts'


/Users/huan/chatie/wechaty-puppet-lark/src/puppet-lark.ts
  139:7   error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys
  161:7   error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys
  165:7   error  Expected object keys to be in ascending order. 'data' should be before 'url'                sort-keys
  175:7   error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys
  180:7   error  Expected object keys to be in ascending order. 'data' should be before 'url'                sort-keys
  183:9   error  Expected object keys to be in ascending order. 'department_ids' should be before 'open_id'  sort-keys
  197:7   error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys
  202:7   error  Expected object keys to be in ascending order. 'data' should be before 'url'                sort-keys
  224:7   error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys
  229:7   error  Expected object keys to be in ascending order. 'data' should be before 'url'                sort-keys
  232:9   error  Expected object keys to be in ascending order. 'department_ids' should be before 'open_id'  sort-keys
  258:7   error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys
  336:7   error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys
  340:7   error  Expected object keys to be in ascending order. 'data' should be before 'url'                sort-keys
  355:7   error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys
  359:7   error  Expected object keys to be in ascending order. 'data' should be before 'url'                sort-keys
  388:9   error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys
  393:9   error  Expected object keys to be in ascending order. 'data' should be before 'url'                sort-keys
  397:11  error  Expected object keys to be in ascending order. 'content' should be before 'msg_type'        sort-keys
  418:7   error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys
  423:7   error  Expected object keys to be in ascending order. 'data' should be before 'url'                sort-keys
  427:9   error  Expected object keys to be in ascending order. 'content' should be before 'msg_type'        sort-keys
  438:7   error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys
  443:7   error  Expected object keys to be in ascending order. 'data' should be before 'url'                sort-keys
  447:9   error  Expected object keys to be in ascending order. 'content' should be before 'msg_type'        sort-keys
  466:7   error  Expected object keys to be in ascending order. 'file' should be before 'image'              sort-keys
  473:7   error  Expected object keys to be in ascending order. 'fromId' should be before 'timestamp'        sort-keys
  485:7   error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys
  490:7   error  Expected object keys to be in ascending order. 'data' should be before 'url'                sort-keys
  509:7   error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys
  514:7   error  Expected object keys to be in ascending order. 'data' should be before 'url'                sort-keys
  531:7   error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys
  536:7   error  Expected object keys to be in ascending order. 'data' should be before 'url'                sort-keys
  555:7   error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys
  560:7   error  Expected object keys to be in ascending order. 'data' should be before 'url'                sort-keys
  577:7   error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys
  588:11  error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys
  592:11  error  Expected object keys to be in ascending order. 'data' should be before 'url'                sort-keys
  617:7   error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys
  622:7   error  Expected object keys to be in ascending order. 'data' should be before 'url'                sort-keys
  641:9   error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys
  646:9   error  Expected object keys to be in ascending order. 'data' should be before 'url'                sort-keys
  656:9   error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys
  660:9   error  Expected object keys to be in ascending order. 'data' should be before 'url'                sort-keys
  687:7   error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys
  691:7   error  Expected object keys to be in ascending order. 'data' should be before 'url'                sort-keys
  709:7   error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys
  713:7   error  Expected object keys to be in ascending order. 'data' should be before 'url'                sort-keys
  731:7   error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys
  736:7   error  Expected object keys to be in ascending order. 'data' should be before 'url'                sort-keys
  750:7   error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys
  754:7   error  Expected object keys to be in ascending order. 'data' should be before 'url'                sort-keys
  773:9   error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys
  777:9   error  Expected object keys to be in ascending order. 'data' should be before 'url'                sort-keys
  794:7   error  Expected object keys to be in ascending order. 'headers' should be before 'method'          sort-keys

✖ 55 problems (55 errors, 0 warnings)

npm ERR! code 1
npm ERR! path /Users/huan/chatie/wechaty-puppet-lark
npm ERR! command failed
npm ERR! command sh -c eslint --ignore-pattern fixtures/ 'src/**/*.ts' 'tests/**/*.ts'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/huan/.npm/_logs/2021-01-11T13_41_18_165Z-debug.log
npm ERR! code 1
npm ERR! path /Users/huan/chatie/wechaty-puppet-lark
npm ERR! command failed
npm ERR! command sh -c npm run lint:es && npm run lint:ts && npm run lint:md

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/huan/.npm/_logs/2021-01-11T13_41_18_191Z-debug.log
npm ERR! code 1
npm ERR! path /Users/huan/chatie/wechaty-puppet-lark
npm ERR! command failed
npm ERR! command sh -c npm run lint && npm run test:unit

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/huan/.npm/_logs/2021-01-11T13_41_18_218Z-debug.log
```

**Comment by huan** [comment]
And the GitHub Actions shows the same output at <https://github.com/wechaty/wechaty-puppet-lark/runs/1680755043?check_suite_focus=true#step:5:17>

**Comment by Roxanne718** [comment]
I run npm test but got this:


`> wechaty-pguppet-lark@0.3.1 test D:\Projects\Wechaty\wechaty-puppet-lark
> npm run lint && npm run test:unit


> wechaty-pguppet-lark@0.3.1 lint D:\Projects\Wechaty\wechaty-puppet-lark
> npm run lint:es && npm run lint:ts && npm run lint:md


> wechaty-pguppet-lark@0.3.1 lint:es D:\Projects\Wechaty\wechaty-puppet-lark
> eslint --ignore-pattern fixtures/ 'src/**/*.ts' 'tests/**/*.ts'


Oops! Something went wrong! :(

ESLint: 7.17.0

No files matching the pattern "'src/**/*.ts'" were found.
Please check for typing mistakes in the pattern.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! wechaty-pguppet-lark@0.3.1 lint:es: `eslint --ignore-pattern fixtures/ 'src/**/*.ts' 'tests/**/*.ts'`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the wechaty-pguppet-lark@0.3.1 lint:es script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rui.LAPTOP-K9989SLH\AppData\Roaming\npm-cache\_logs\2021-01-12T06_57_22_090Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! wechaty-pguppet-lark@0.3.1 lint: `npm run lint:es && npm run lint:ts && npm run lint:md`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the wechaty-pguppet-lark@0.3.1 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rui.LAPTOP-K9989SLH\AppData\Roaming\npm-cache\_logs\2021-01-12T06_57_22_179Z-debug.log
npm ERR! Test failed.  See above for more details.
`

**Comment by huan** [comment]
Please post the output of `node --version` and `npm --version` in your system.

I'd like to suggest that you to install the node v14 with the latest version of npm, then run `rm -fr node_modules && npm install && npm test` to see if the problem can be solved.

**Comment by huan** [comment]
Kindly ping

Just want to know did you get the lining script ran on your local environment successfully?

**Comment by Roxanne718** [comment]
I'm sorry I didn't see this message.
I run `rm -fr node_modules && npm install && npm test` but the question still bothers me.
Here is details.

> >node --version
> v14.15.4

> >npm --version
> 6.14.11

**Comment by huan** [comment]
That's wired.

Could you please post all the output messages when running `rm -fr node_modules && npm install && npm test` ?

And can you try running this on another windows computer, or a linux server?

**Comment by Roxanne718** [comment]
Here are outputs. I‘m sorry I have no chance to use another computer recently.

> D:\Projects\Wechaty\wechaty-puppet-lark>rm -rf node_modules

> D:\Projects\Wechaty\wechaty-puppet-lark>npm install

'''
> grpc@1.24.4 install D:\Projects\Wechaty\wechaty-puppet-lark\node_modules\grpc
> node-pre-gyp install --fallback-to-build --library=static_library

node-pre-gyp WARN Using request for node-pre-gyp https download 
[grpc] Success: "D:\Projects\Wechaty\wechaty-puppet-lark\node_modules\grpc\src\node\extension_binary\node-v83-win32-x64-u

> core-js@2.6.12 postinstall D:\Projects\Wechaty\wechaty-puppet-lark\node_modules\core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> git-scripts@0.4.3 postinstall D:\Projects\Wechaty\wechaty-puppet-lark\node_modules\git-scripts
> node bin/install


> node-jq@1.12.0 postinstall D:\Projects\Wechaty\wechaty-puppet-lark\node_modules\node-jq
> npm run install-binary


> node-jq@1.12.0 install-binary D:\Projects\Wechaty\wechaty-puppet-lark\node_modules\node-jq
> node scripts/install-binary.js

Downloading jq from https://github.com/stedolan/jq/releases/download/jq-1.6/jq-win64.exe
Downloaded in D:\Projects\Wechaty\wechaty-puppet-lark\node_modules\node-jq\bin

> @chatie/eslint-config@0.12.1 postinstall D:\Projects\Wechaty\wechaty-puppet-lark\node_modules\@chatie\eslint-config
> node bin/install.js


> @chatie/git-scripts@0.6.2 postinstall D:\Projects\Wechaty\wechaty-puppet-lark\node_modules\@chatie\git-scripts
> node scripts/install.js


> @chatie/tsconfig@0.11.4 postinstall D:\Projects\Wechaty\wechaty-puppet-lark\node_modules\@chatie\tsconfig
> node bin/install.js


> wechaty@0.50.7 postinstall D:\Projects\Wechaty\wechaty-puppet-lark\node_modules\wechaty
> opencollective-postinstall

Thank you for using wechaty!
If you rely on this package, please consider supporting our open collective:
> https://opencollective.com/wechaty/donate

added 983 packages from 985 contributors and audited 984 packages in 36.048s

77 packages are looking for funding
  run `npm fund` for details

found 5 vulnerabilities (3 low, 1 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
'''

> D:\Projects\Wechaty\wechaty-puppet-lark>npm test
'''
> wechaty-pguppet-lark@0.3.1 test D:\Projects\Wechaty\wechaty-puppet-lark
> npm run lint && npm run test:unit


> wechaty-pguppet-lark@0.3.1 lint D:\Projects\Wechaty\wechaty-puppet-lark


Oops! Something went wrong! :(

ESLint: 7.17.0

No files matching the pattern "'src/**/*.ts'" were found.
Please check for typing mistakes in the pattern.

npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! wechaty-pguppet-lark@0.3.1 lint:es: `eslint --ignore-pattern fixtures/ 'src/**/*.ts' 'tests/**/*.ts'`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the wechaty-pguppet-lark@0.3.1 lint:es script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rui.LAPTOP-K9989SLH\AppData\Roaming\npm-cache\_logs\2021-01-22T02_15_33_081Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! wechaty-pguppet-lark@0.3.1 lint: `npm run lint:es && npm run lint:ts && npm run lint:md`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the wechaty-pguppet-lark@0.3.1 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rui.LAPTOP-K9989SLH\AppData\Roaming\npm-cache\_logs\2021-01-22T02_15_33_155Z-debug.log
npm ERR! Test failed.  See above for more details.
'''

**Comment by huan** [comment]
It seems that your windows environment has some problems with Node.js.

Do you have an ssh pub key? If you have one, please set it to your GitHub account, or send it to me.

We have a Wechaty Contributor Server that you can use as a development environment. (Ubuntu Linux)

See: https://github.com/wechaty/PMC/issues/13

**Comment by huan** [comment]
Kindly ping @Roxanne718 

Do we have any new progress on this issue?

Let's fix those linting problems in the following days so that we can keep moving on! 💪

**Comment by huan** [comment]
Thanks for the great work from @Roxanne718 , all linting problems have been resolved!

The latest master branch code was CI/CD to NPM now.
